baseURL = 'https://averystampp.com/'
languageCode = 'en-us'
title = 'Avery Stampps Blog'

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages.en]
  languageName = "English"
  locale = "en-US"
  weight = 1

[languages.ru]
  languageName = "Русский"
  locale = "ru-RU"
  weight = 2

